engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
  csslint:
    enabled: true
  git-legal:
    enabled: true
    
ratings:
   paths:
   - "Gemfile*"
   - "*.gemspec"
   - "package.json"
   - "yarn.lock"
   - "requirements.txt"
   - "composer.*"
   - "**.css"

