engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
engines:
  csslint:
    enabled: true
  ratings:
    paths:
      - "**.css"
engines:
  git-legal:
    enabled: true 
  ratings:
    paths:
      - "Gemfile*"
      - "*.gemspec"
      - "package.json"
      - "yarn.lock"
      - "requirements.txt"
      - "composer.*"
